OdessaMasonFireworks/OdessaMasonFireworks.UI.MVC/Models/ContactViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace OdessaMasonFireworks.UI.MVC.Models
{
    public class ContactViewModel
    {
        [Required(ErrorMessage = "*Required")]
        public string Name { get; set; } = null!;

        [Required(ErrorMessage = "*Required")]
        [DataType(DataType.EmailAddress)]//enforces standard emil formatting
        public string Email { get; set; } = null!;

        [Required(ErrorMessage = "*Required")]
        public string Subject { get; set; } = null!;

        [Required(ErrorMessage = "*Required")]
        [DataType(DataType.MultilineText)]//gives us a larger textbox (textarea in HTML)
        public string Message { get; set; } = null!;
    }
}

OdessaMasonFireworks/OdessaMasonFireworks.UI.MVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using OdessaMasonFireworks.UI.MVC.Models;
using System.Diagnostics;
using System.Net.Mail;
using MimeKit;
using MailKit.Net.Smtp;
using SmtpClient = MailKit.Net.Smtp.SmtpClient;

namespace OdessaMasonFireworks.UI.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        private readonly IConfiguration _config;

        public HomeController(ILogger<HomeController> logger, IConfiguration config)
        {
            _logger = logger;
            _config = config;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Contact(ContactViewModel cvm)
        {
            //when a class has validation attributes, that validation should be checked
            //BEFORE attempting to process any of the data they provided.
            if (!ModelState.IsValid)
            {
                //Send them back to the form. we can pass the object to the view
                //so the form will contain the original info they provided.
                return View(cvm);
            }
            //To handle sending the email, we'll need to install a NuGet package.

            //MIME -> Multipurpose Internet Mail Extensions - Allows email to contain
            //info other thatn ASCII -> Audio, Video, Images, and HTML

            //SMTP - Simple Mail Transfer Protocol -> unencrytped - an internet protocol
            //like HTTP that specializes in the collection & transfer of email data

            #region Email Setup Steps & Email Info
            //1. Go to Tools > NuGet Package Manager > Manage NuGet Packages for Solution
            //2. Go to the Browse tab and search for NETCore.MailKit
            //3. Click NETCore.MailKit
            //4. On the right, check the box next to the CORE1 project, then click "Install"
            //5. Once installed, return here
            //6. Add the following using statements & comments:
            //      - using MimeKit; //Added for access to MimeMessage class
            //      - using MailKit.Net.Smtp; //Added for access to SmtpClient class
            //7. Once added, return here to continue coding email functionality
            #endregion

            //create and format the message content we will receive from the contact form.
            string message = $"You have received a new email from your site's contact form!<br>" +
                $"Sender: {cvm.Name}<br>" +
                $"Email: {cvm.Email}<br>" +
                $"Message: {cvm.Message}";

            //Build a MimeMessage object to assist with transporting the email info.
            var mm = new MimeMessage();

            //We can access the credentials for this email user from our appsettings.json file
            mm.From.Add(new MailboxAddress("Sender", _config.GetValue<string>("Credentials:Email:User")));

            mm.To.Add(new MailboxAddress("Personal", _config.GetValue<string>("Credentials:Email:Recipient")));

            mm.ReplyTo.Add(new MailboxAddress("User", cvm.Email));

            mm.Subject = cvm.Subject;

            //the body of the message will be formatted with the string we created above
            mm.Body = new TextPart("HTML") { Text = message };

            //we can set the prio of a message to "Urgent" so it will be flagged in our email client.
            mm.Priority = MessagePriority.Urgent;

            //using directive - create the SmtpClient object used to actully send the email.
            //Once all of the code is done, it will clise any open connections and dispose of the object
            //for us
            using (var client = new SmtpClient())
            {
                try
                {
                    //connect to the mail server using the credentials in our appesttings.json
                    //client.Connect(_config.GetValue<string>("Credentials:Email:Client"));
                    // should be port 25. if blocked uncomment below
                    //handle alt ports
                    client.Connect(_config.GetValue<string>("Credentials:Email:Client"), 8889);

                    //login to the mail server using your credentials
                    client.Authenticate(
                        //UserName
                        _config.GetValue<string>("Credentials:Email:User"),
                        //Password
                        _config.GetValue<string>("Credentials:Email:Password")
                        );
                    //send the email
                    client.Send(mm);
                }
                //handle any issues.
                catch (Exception ex)
                {
                    //if there are ANY issues, we can store an error message in a ViewBag variable
                    //and display in the view
                    ViewBag.ErrorMessage = $"There was an error processing your request. Please try again later.<br>Error Message: {ex.Message}";

                    return View(cvm);
                }//end try catch
            }//end using
            //if all goes well, return a view that displays a confirmation message to the user that their email was sent.
            return View("EmailConfirmation", cvm);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

OdessaMasonFireworks/OdessaMasonFireworks.UI.MVC/Controllers/MembersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OdessaMasonFireworks.DATA.EF.Models;
using OdessaMasonFireworks.UI.MVC.Utilities;

namespace OdessaMasonFireworks.UI.MVC.Controllers
{

    public class MembersController : Controller
    {
        private readonly OdessaMasonFireworksContext _context;
        private readonly IWebHostEnvironment _webHostEnviroment;

        public MembersController(OdessaMasonFireworksContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnviroment = webHostEnvironment;
        }

        [Authorize(Roles = "Admin")]
        // GET: Members
        public async Task<IActionResult> Index()
        {
            return _context.Members != null ?
                        View(await _context.Members.ToListAsync()) :
                        Problem("Entity set 'OdessaMasonFireworksContext.Members'  is null.");
        }

        public IActionResult Rent()
        {
            return View();
        }

        public async Task<IActionResult> TiledMembers()
        {
            return _context.Members != null ?
                         View(await _context.Members.ToListAsync()) :
                         Problem("Entity set 'OdessaMasonFireworksContext.Members'  is null.");
        }

        [Authorize(Roles = "Admin")]
        // GET: Members/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Members == null)
            {
                return NotFound();
            }

            var member = await _context.Members
                .FirstOrDefaultAsync(m => m.MemberId == id);
            if (member == null)
            {
                return NotFound();
            }

            return View(member);
        }

        [Authorize(Roles = "Admin")]
        // GET: Members/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Members/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MemberId,FirstName,LastName,Position,JoinDate,Address,City,State,PostalCode,Email,Phone,MemberImage,Image")] Member member)
        {
            if (ModelState.IsValid)
            {
                if (member.Image != null)
                {
                    string ext = Path.GetExtension(member.Image.FileName);
                    string[] validExts = { ".jpeg", ".jpg", ".gif", ".png", ".webp", ".jfif" };

                    if (validExts.Contains(ext.ToLower()) && member.Image.Length < 4_194_303)
                    {
                        member.MemberImage = Guid.NewGuid() + ext;
                        string webRootPath = _webHostEnviroment.WebRootPath;
                        string fullImagePath = webRootPath + "/images/";
                        using (var memoryStream = new MemoryStream())
                        {
                            await member.Image.CopyToAsync(memoryStream);

                            using (var img = Image.FromStream(memoryStream))
                            {
                                int maxImageSize = 500;
                                int maxThumbSize = 100;

                                ImageUtility.ResizeImage(fullImagePath, member.MemberImage, img, maxImageSize, maxThumbSize);
                            }
                        }
                    }
                }
                else
                {
                    member.MemberImage = "NoImage.png";
                }
                _context.Add(member);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(member);
        }

        [Authorize(Roles = "Admin")]
        // GET: Members/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Members == null)
            {
                return NotFound();
            }

            var member = await _context.Members.FindAsync(id);
            if (member == null)
            {
                return NotFound();
            }
            return View(member);
        }

        // POST: Members/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MemberId,FirstName,LastName,Position,JoinDate,Address,City,State,PostalCode,Email,Phone,MemberImage,Image")] Member member)
        {
            if (id != member.MemberId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                string oldImageName = member.MemberImage;

                if (member.Image != null)
                {
                    string ext = Path.GetExtension(member.Image.FileName);

                    string[] validExts = { ".jpeg", ".jpg", ".png", ".gif", ".webp", ".jfif" };

                    if (validExts.Contains(ext.ToLower()) && member.Image.Length < 4_194_303)
                    {
                        member.MemberImage = Guid.NewGuid() + ext;
                        string webRootPath = _webHostEnviroment.WebRootPath;
                        string fullPath = webRootPath + "/images/";

                        if (oldImageName != "NoImage.png")
                        {
                            ImageUtility.Delete(fullPath, oldImageName);
                        }

                        using (var memoryStream = new MemoryStream())
                        {
                            await member.Image.CopyToAsync(memoryStream);
                            using (var img = Image.FromStream(memoryStream))
                            {
                                int maxImageSize = 500;
                                int maxThumbSize = 100;
                                ImageUtility.ResizeImage(fullPath, member.MemberImage, img, maxImageSize, maxThumbSize);
                            }
                        }

                    }
                }
                try
                {
                    _context.Update(member);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MemberExists(member.MemberId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(member);
        }

        [Authorize(Roles = "Admin")]
        // GET: Members/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Members == null)
            {
                return NotFound();
            }

            var member = await _context.Members
                .FirstOrDefaultAsync(m => m.MemberId == id);
            if (member == null)
            {
                return NotFound();
            }

            return View(member);
        }

        [Authorize(Roles = "Admin")]
        public JsonResult AjaxDelete(int id)
        {
            Member member = _context.Members.Find(id);
            _context.Members.Remove(member);
            _context.SaveChanges();

            string confirmMessage = $"Deleted {member.FirstName + " " + member.LastName} from the database.";
            return Json(new { id = id, message = confirmMessage });
        }

        // POST: Members/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Members == null)
            {
                return Problem("Entity set 'OdessaMasonFireworksContext.Members'  is null.");
            }
            var member = await _context.Members.FindAsync(id);
            if (member != null)
            {
                _context.Members.Remove(member);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MemberExists(int id)
        {
            return (_context.Members?.Any(e => e.MemberId == id)).GetValueOrDefault();
        }
    }
}

OdessaMasonFireworks/OdessaMasonFireworks.UI.MVC/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}

@model OdessaMasonFireworks.UI.MVC.Models.ContactViewModel
<br />
<br />
<br />
<!-- Contact Section-->
<section class="page-section fadein" id="contact">
    <div class="container">
        <!-- Contact Section Heading-->
        <h2 class="page-section-heading flex text-center text-uppercase text-secondary mb-3 custom-gold custom-blue rounded-2 p-1">Contact Us</h2>
        <!-- Icon Divider-->
        <div class="divider-custom">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>
        <!-- Contact Section Form-->
        <div class="row justify-content-center">
            <div class="col-lg-8 col-xl-7">
                <form asp-action="Contact">
                    <!-- Name input-->
                    <div class="form-floating mb-3 ">
                        <input asp-for="Name" class="form-control" />
                        <label asp-for="Name" class="control-label"></label>
                        <span asp-validation-for="Name" class="text-danger"></span>
                        <div class="invalid-feedback" data-sb-feedback="name:required">A name is required.</div>
                    </div>
                    <!-- Email address input-->
                    <div class="form-floating mb-3">
                        <input asp-for="Email" class="form-control" />
                        <label asp-for="Email" class="control-label"></label>
                        <span asp-validation-for="Email" class="text-danger"></span>
                        <div class="invalid-feedback" data-sb-feedback="email:required">An email is required.</div>
                        <div class="invalid-feedback" data-sb-feedback="email:email">Email is not valid.</div>
                    </div>
                    <!-- Phone number input-->
                    <div class="form-floating mb-3">
                        <input asp-for="Subject" class="form-control" />
                        <label asp-for="Subject" class="control-label"></label>
                        <span asp-validation-for="Subject" class="text-danger"></span>
                        <div class="invalid-feedback" data-sb-feedback="phone:required">A phone number is required.</div>
                    </div>
                    <!-- Message input-->
                    <div class="form-floating mb-3">
                        <textarea asp-for="Message" class="form-control"></textarea>
                        <label asp-for="Message" class="control-label"></label>
                        <span asp-validation-for="Message" class="text-danger"></span>
                        <div class="invalid-feedback" data-sb-feedback="message:required">A message is required.</div>
                    </div>
                    <!-- Submit Button-->
                    <input type="submit" value="Send" class="btn custom-blue custom-gold" />
                </form>
            </div>
        </div>
    </div>
</section>

OdessaMasonFireworks/OdessaMasonFireworks.UI.MVC/Views/Home/EmailConfirmation.cshtml
@{
    ViewBag.Title = "Email Confirmation";
}
@model OdessaMasonFireworks.UI.MVC.Models.ContactViewModel
<br />
<br />
<br />
<br />
<br />
<main id="main">
    <!-- ======= Confirmation Section ======= -->
    <section class="contact fadein" data-aos="fade-up" data-aos-easing="ease-in-out" data-aos-duration="500">
        <div class="container">
            <div class="row">

                <div class="col-lg-12 custom-blue custom-gold rounded-2">

                    <div class="info-box">
                        <i class="bx bx-check-circle"></i>
                        <h3 class="custom-gold">Message Sent!</h3>
                        <p>
                            @* When referring to a specific object that fits the model (like the cvm object in the controller), use a capital M -- "Model" *@
                            Thank you for contacting us, we will respond to
                            your message using the provided email address, @Model.Email, in
                            the next 1-3 business days.
                        </p>

                        <br />

                        <div class="offset-3 col-md-6 text-center">
                            <p>
                                You sent the following message on
                                @DateTime.Now.Date.ToShortDateString() at
                                @DateTime.Now.ToShortTimeString() :
                            </p>
                        </div>

                        <br />

                        <div class="offset-3 col-md-6">
                            <p>
                                <em>@Model.Message</em>
                            </p>
                        </div>

                    </div>

                </div>

            </div>

        </div>
    </section>
</main><!-- End #main -->

OdessaMasonFireworks/OdessaMasonFireworks.UI.MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}



<!-- Header-->
<header class="py-5">
    <div class="container px-5">
        <div class="row gx-5 align-items-center justify-content-center fadein">
            <div class="col-lg-8 col-xl-7 col-xxl-6">
                <div class="my-5 text-center text-xl-start">
                    <h1 class="display-5 fw-bolder  mb-2 custom-gold text-center">Mt. Hope Masonic Lodge Odessa Missouri</h1>
                    <p class="lead fw-normal custom-gold text-center mb-4">Located at 6898 N 131 Hwy in Odessa MO, this brotherhood has a focus to help the surrounding community, such as giving scholarships, and hosting a breakfast with santa.</p>
                    <div class="d-grid gap-3 d-sm-flex justify-content-sm-center justify-content-xl-start">
                        <a class="btn custom-blue btn-lg px-4 custom-gold" asp-action="Rent" asp-controller="Members">Rent our lodge</a>
                        <a class="btn custom-blue btn-lg px-4 custom-gold" asp-action="Contact" asp-controller="Home">Contact us</a>
@*                        <a class="btn custom-blue btn-lg px-4 custom-gold" asp-action="TiledMembers" asp-controller="Members">Our members</a>
*@                    </div>
                </div>
            </div>
            <div class="col-xl-5 col-xxl-6 d-none d-xl-block text-center"><img class="insignia rounded-5 my-5" src="~/assets/lodgeinsignia.jpg" alt="..." /></div>
        </div>
    </div>
</header>
<!-- Testimonial section-->
<div class="py-1 bg-light fadein">
    <div class="container px-5 my-4">
        <div class="row gx-5 justify-content-center">
            <div class="col-lg-10 col-xl-7">
                <div class="text-center">
                    <div class="fs-4 mb-4 fst-italic">“To enlarge the sphere of social happiness is worthy of the benevolent design of a Masonic institution; and it is most fervently to be wished, that the conduct of every member of the fraternity, as well as those publications, that discover the principles which actuate them, may tend to convince mankind that the grand object of Masonry is to promote the happiness of the human race.”</div>
                    <div class="d-flex align-items-center justify-content-center">
                        <img class="rounded-circle me-3" style="height: 40px; width: 40px;" src="/assets/GW.jpg" alt="..." />
                        <div class="fw-bold">
                            George Washington
                            <span class="fw-bold text-primary mx-1">/</span>
                            1st President of the United States of America
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Features section-->
<section class="py-5 fadein" id="features">
    <div class="container px-5 my-5">
        <div class="row gx-5">
            <div class="col-lg-4 mb-5 mb-lg-0"><h2 class="fw-bolder mb-0 custom-gold text-center">Giving to the community that serves us.</h2></div>
            <div class="col-lg-8">
                <div class="row gx-5 row-cols-1 row-cols-md-2">
                    <div class="col mb-5 h-100 smallcenter">
                        <div class="feature custom-blue custom-gold rounded-3 mb-3"><i class="bi bi-cash-stack"></i></div>
                        <h2 class="h5 custom-gold">Scholarships</h2>
                        <p class="mb-0 custom-gold">Helping those who show excellent potential, by working hard and creating opportunities.</p>
                    </div>
                    <div class="col mb-5 h-100 smallcenter">
                        <div class="feature custom-blue custom-gold rounded-3 mb-3"><i class="bi bi-gift"></i></div>
                        <h2 class="h5 custom-gold">Breakfast with Santa</h2>
                        <p class="mb-0 custom-gold">Feeding and giving gifts to those who may not be able to do it themselves.</p>
                    </div>
                    <div class="col mb-5 h-100 smallcenter">
                        <div class="feature custom-blue custom-gold rounded-3 mb-3"><i class="bi bi-bank"></i></div>
                        <h2 class="h5 custom-gold">Renting</h2>
                        <p class="mb-0 custom-gold">Renting our lodge to ensure that memories are made.</p>
                    </div>
                    <div class="col mb-5 mb-md-0 h-100 smallcenter">
                        <div class="feature custom-gold custom-blue rounded-3 mb-3"><i class="bi bi-currency-dollar"></i></div>
                        <h2 class="h5 custom-gold">Fireworks</h2>
                        <p class="mb-0 custom-gold">Selling fireworks at the lowest prices to make sure that everyone can celebrate indenpendence.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Blog preview section-->
@*<section class="py-5">
    <div class="container px-5 my-5">
        <div class="row gx-5 justify-content-center">
            <div class="col-lg-8 col-xl-6">
                <div class="text-center">
                    <h2 class="fw-bolder">From our blog</h2>
                    <p class="lead fw-normal text-muted mb-5">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eaque fugit ratione dicta mollitia. Officiis ad.</p>
                </div>
            </div>
        </div>
        <div class="row gx-5">
            <div class="col-lg-4 mb-5">
                <div class="card h-100 shadow border-0">
                    <img class="card-img-top" src="https://dummyimage.com/600x350/ced4da/6c757d" alt="..." />
                    <div class="card-body p-4">
                        <div class="badge bg-primary bg-gradient rounded-pill mb-2">News</div>
                        <a class="text-decoration-none link-dark stretched-link" href="#!"><h5 class="card-title mb-3">Blog post title</h5></a>
                        <p class="card-text mb-0">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    </div>
                    <div class="card-footer p-4 pt-0 bg-transparent border-top-0">
                        <div class="d-flex align-items-end justify-content-between">
                            <div class="d-flex align-items-center">
                                <img class="rounded-circle me-3" src="https://dummyimage.com/40x40/ced4da/6c757d" alt="..." />
                                <div class="small">
                                    <div class="fw-bold">Kelly Rowan</div>
                                    <div class="text-muted">March 12, 2023 &middot; 6 min read</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 mb-5">
                <div class="card h-100 shadow border-0">
                    <img class="card-img-top" src="https://dummyimage.com/600x350/adb5bd/495057" alt="..." />
                    <div class="card-body p-4">
                        <div class="badge bg-primary bg-gradient rounded-pill mb-2">Media</div>
                        <a class="text-decoration-none link-dark stretched-link" href="#!"><h5 class="card-title mb-3">Another blog post title</h5></a>
                        <p class="card-text mb-0">This text is a bit longer to illustrate the adaptive height of each card. Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    </div>
                    <div class="card-footer p-4 pt-0 bg-transparent border-top-0">
                        <div class="d-flex align-items-end justify-content-between">
                            <div class="d-flex align-items-center">
                                <img class="rounded-circle me-3" src="https://dummyimage.com/40x40/ced4da/6c757d" alt="..." />
                                <div class="small">
                                    <div class="fw-bold">Josiah Barclay</div>
                                    <div class="text-muted">March 23, 2023 &middot; 4 min read</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 mb-5">
                <div class="card h-100 shadow border-0">
                    <img class="card-img-top" src="https://dummyimage.com/600x350/6c757d/343a40" alt="..." />
                    <div class="card-body p-4">
                        <div class="badge bg-primary bg-gradient rounded-pill mb-2">News</div>
                        <a class="text-decoration-none link-dark stretched-link" href="#!"><h5 class="card-title mb-3">The last blog post title is a little bit longer than the others</h5></a>
                        <p class="card-text mb-0">Some more quick example text to build on the card title and make up the bulk of the card's content.</p>
                    </div>
                    <div class="card-footer p-4 pt-0 bg-transparent border-top-0">
                        <div class="d-flex align-items-end justify-content-between">
                            <div class="d-flex align-items-center">
                                <img class="rounded-circle me-3" src="https://dummyimage.com/40x40/ced4da/6c757d" alt="..." />
                                <div class="small">
                                    <div class="fw-bold">Evelyn Martinez</div>
                                    <div class="text-muted">April 2, 2023 &middot; 10 min read</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Call to action-->
        <aside class="bg-primary bg-gradient rounded-3 p-4 p-sm-5 mt-5">
            <div class="d-flex align-items-center justify-content-between flex-column flex-xl-row text-center text-xl-start">
                <div class="mb-4 mb-xl-0">
                    <div class="fs-3 fw-bold text-white">New products, delivered to you.</div>
                    <div class="text-white-50">Sign up for our newsletter for the latest updates.</div>
                </div>
                <div class="ms-xl-4">
                    <div class="input-group mb-2">
                        <input class="form-control" type="text" placeholder="Email address..." aria-label="Email address..." aria-describedby="button-newsletter" />
                        <button class="btn btn-outline-light" id="button-newsletter" type="button">Sign up</button>
                    </div>
                    <div class="small text-white-50">We care about privacy, and will never share your data.</div>
                </div>
            </div>
        </aside>
    </div>
</section>*@